

/**
 * Sottoinsieme del contesto docente passato a gemini.ts.
 * Contiene solo i campi dati letti dal servizio AI (no handler, no isLoading).
 */
export interface MasterContextData {
    systemInstruction: string;
    constitution: string;
    crewContext: string;
    rulesContext: string;
    teacherProfile: string;
}

/**
 * Una settimana nel calendario de La Rotta.
 * mondayDate: ISO string della data del lunedì (es. "2025-09-15").
 * activeBlocks: array 1-indexed dei blocchi presenti (es. [1,2,3] oppure [1,3] se BL2 è assente).
 */
export interface WeekEntry {
    weekNumber: number;
    mondayDate: string;
    activeBlocks: number[];
}

export interface GroundingSource {
    uri: string;
    title: string;
}

export interface Attachment {
    name: string;
    type: string; // Mime type
    data: string; // Base64 data URL
}

export interface Evaluation {
    date: string;
    value: string; // e.g., "Ottimo", "Sotto soglia", "7/10"
    notes: string;
    // New optional fields for logbook
    weekNumber?: number;
    blockIndex?: number;
    module?: string;
    pillar?: string;
}

export interface Student {
    id: string;
    name: string;
    notes?: string;
    evaluations: Evaluation[];
    adaSummary?: {
        content: string;
        date: string; // ISO string
    };
}

export interface WeekRouteInfo {
    weekNumber: number;
    dates: string;
    totalBlocks: number;
    notes?: string;
}

// --- TIPI AGGIORNATI PER LA PIANIFICAZIONE DETTAGLIATA ---

export type BlockStatus = 'normale' | 'saltato' | 'da definire' | 'annullato';

export type LessonType =
  | 'frontale_teorica'
  | 'frontale_operativa'
  | 'laboratorio'
  | 'verifica'
  | 'discussione'
  | 'uda'
  | 'fsl';

/** Ciclo di vita di una lezione: pianificata → in corso → archiviata */
export type LessonState = 'progettata' | 'in_corso' | 'archiviata';

export interface Pillar {
    name: string;
}

export interface ModuleDetails {
    name: string;
    role: string;
    significance: string;
    sintonizzazione: Pillar[];
    operativi: Pillar[];
    attivitaChiave: string[];
}

export interface ParsedConstitution {
    modules: ModuleDetails[];
    moduleMap: Map<string, ModuleDetails>;
}

export interface GroupDefinition {
    name: string;
    studentIds: string[];
    justification?: string;
    notes?: string;
    isComplete?: boolean;
    completionDate?: string; // ISO String
    addedStudentIds?: string[];
}

export interface BlockAllocation {
    type: 'group' | 'individual';
    // A flexible structure for now, can be typed more strictly later
    data: {
        groups?: GroupDefinition[];
        individualAssignments?: { studentId: string; objective: string }[];
    }
}

export interface ContentBlock {
    id: string;
    content: string;
}

export interface AdaAnalysis {
    performance: string;
    highlightedStudents: string[];
    difficulties: string[];
    suggestion: string;
}

export type BlockSourceType = 'url' | 'note' | 'pdf';

export interface BlockSource {
    id: string;                     // generato con crypto.randomUUID()
    type: BlockSourceType;
    title: string;                  // nome editabile dall'insegnante
    addedAt: number;                // timestamp ms (Date.now())
    origin: 'manual' | 'promoted'; // 'promoted' = promossa dalla Webliografia automatica
    // type === 'url'
    url?: string;
    // type === 'note'
    content?: string;
    // type === 'pdf'
    fileName?: string;
    fileSize?: number;
    geminiFileId?: string;          // ID restituito da Gemini File API
    geminiFileExpiry?: number;      // timestamp ms scadenza (48h da upload)
    dbFileKey?: string;             // chiave nello store IndexedDB 'blockFiles'
}

export interface BlockDetails {
    id: string;
    day: string;
    status: BlockStatus;
    reason?: string; // For 'saltato' status
    module?: string;
    objective?: string;
    constitutionSummary?: string; // For export headers
    moduleDetails?: ModuleDetails;
    contentBlocks?: ContentBlock[];
    messages?: Message[]; // Each block has its own chat history
    allocations?: BlockAllocation; // For group/individual work
    presentStudentIds?: string[];
    isReviewed?: boolean; // For tracking consuntivo
    artifacts?: string[]; // For tracking generated outputs in "In Aula" view
    lessonNotes?: string; // Qualitative notes about the lesson
    adaAnalysis?: AdaAnalysis; // Structured analysis generated by Ada
    usefulLinks?: { id: string; url: string; title: string; }[];
    materialsCloudLink?: string;
    linkedNotebookIds?: string[];
    // Campi per la pianificazione dettagliata nel cruscotto
    lessonTitle?: string;
    lessonSyllabus?: string;
    lessonMaterials?: string;
    isLocked?: boolean;
    projectDeadline?: string; // ISO String for group project deadlines
    lessonState?: LessonState; // Ciclo di vita: progettata → in_corso → archiviata
    fonti?: BlockSource[];
    tipologia?: LessonType;
}

export type WeekPlanStatus = 'in progettazione' | 'progettazione completata' | 'in corso' | 'completata';

export interface WeekPlan {
    weekNumber: number;
    dates: string;
    totalBlocks: number;
    notes?: string;
    theme: string;
    status: WeekPlanStatus;
    blocks: BlockDetails[];
    students: Omit<Student, 'notes' | 'evaluations' | 'adaSummary'>[]; // Use a simpler student stub for weekly plans
    activeBlockIndex: number;
    finalReport?: {
        achievedObjectives: string;
        nextWeekFollowup: string;
    };
    completionStatus?: 'pending' | 'current' | 'completed'; // Manual override to mark week as "done" in dashboard
}

// Fix: Moved LessonWithGroups here to be shared across components.
export interface LessonWithGroups {
    convoId: string;
    weekNumber: number;
    weekTheme: string;
    blockIndex: number;
    blockDay: string;
    blockObjective?: string;
    groups: GroupDefinition[];
    sortableDate: Date;
    weekDates: string;
    projectDeadline?: string;
}

// --- Planning Action Payloads for Type Safety ---
export type UpdateBlockDayPayload = { action: 'update_block_day', blockIndex: number, day: string, updateDefault?: boolean };
export type UpdateObjectivePayload = { action: 'update_objective', blockIndex: number, newObjective: string };
export type InitializeNormalBlockPayload = { action: 'initialize_normal_block', day: string, objective: string, module: string };
export type ArchiveSimpleStatePayload = { action: 'archive_simple_state', day: string, status: 'saltato', reason: string };
export type ValidateAndArchivePayload = { action: 'validate_and_archive', messageId: string };
export type RecordGroupsPayload = { action: 'record_groups', groups: GroupDefinition[] };
// --- Content Block Management Payloads ---
export type AddValidatedContentAsNewBlockPayload = { action: 'add_validated_content_as_new_block', messageId: string };
export type ReplaceEntireMasterContentPayload = { action: 'replace_entire_master_content', messageId: string };
export type DeleteContentBlockPayload = { action: 'delete_content_block', contentBlockId: string };
export type UpdateContentBlockPayload = { action: 'update_content_block', contentBlockId: string, newContent: string };
export type ConsolidateAndUpdateContentPayload = { action: 'consolidate_and_update_content', newContent: string };


export type PlanningActionPayload =
  | InitializeNormalBlockPayload
  | ArchiveSimpleStatePayload
  | ValidateAndArchivePayload
  | RecordGroupsPayload
  | AddValidatedContentAsNewBlockPayload
  | ReplaceEntireMasterContentPayload
  | DeleteContentBlockPayload
  | UpdateContentBlockPayload
  | ConsolidateAndUpdateContentPayload
  | UpdateBlockDayPayload
  | UpdateObjectivePayload;


export interface Action {
    label: string;
    payload: PlanningActionPayload;
}

export interface Message {
  id: string;
  role: 'user' | 'assistant' | 'system';
  content: string;
  sources?: GroundingSource[];
  attachment?: Attachment;
  generatedImages?: string[]; // Array of base64 data URLs
  actions?: Action[];
  actionUsed?: boolean | string; // true (legacy) o la label dell'azione usata es. 'Trasferito' | 'Aggiunto' | 'Sostituito'
}

export interface DetachedLesson {
  id: string;
  sourceBlockId: string;
  sourceWeekNumber: number;
  sourceDay: string;
  objective?: string;
  lessonTitle?: string;
  lessonSyllabus?: string;
  messages?: Message[];
  contentBlocks?: ContentBlock[];
  detachedAt: string;
  distribuita?: boolean;
  archiviata?: boolean;
}

export interface Conversation {
  id: string;
  title: string;
  messages: Message[];
weekPlan?: WeekPlan;
  studentId?: string; // Link to a student's main record
  evaluationState?: 'AWAITING_VALUE' | 'AWAITING_NOTES' | 'AWAITING_REVIEW_NOTES'; // For guided evaluation input
  tempEvaluation?: Partial<Evaluation>;
  pendingContent?: DetachedLesson[];
}

export interface Mode {
  id: 'balanced' | 'formal' | 'creative' | 'analytical' | 'playful' | 'concise';
  label: string;
  stylePrompt: string;
  colorClasses: {
    badge: string;
    text: string;
    hoverBg: string;
  };
  introMessage: string;
}

export interface Notebook {
  id: string;
  title: string;
  url: string;
  notes: string;
  dateAdded: string; // ISO string
  lastAccessed: string | null; // ISO string or null
}

export interface ToolkitCategory {
  id: string;
  name: string;
  order: number;
}

export interface ToolkitShortcut {
  id: string;
  name: string;
  url: string;
  notes: string;
  categoryId: string;
  order: number;
}

// --- NUOVI TIPI PER IL CRUSCOTTO QUALITATIVO ---

export type EnergyLevel = 'Bassa Frequenza' | 'Ritmo di Crociera' | 'Scintilla Creativa';
export type GrowthLevel = 'Da Potenziare' | 'Stabile' | 'Punto di Forza';
export type MasteryLevel = 'Compreso' | 'In Difficoltà';
export type PillarType = 'Sintonizzazione' | 'Operativo' | 'Attività Chiave' | 'Sconosciuto';

export interface InferredClassEnergy {
    weekNumber: number;
    energyLevel: EnergyLevel;
}

export interface InferredStudentGrowth {
    studentName: string;
    criteria: {
        QualitàElaborati: GrowthLevel;
        Partecipazione: GrowthLevel;
        Collaborazione: GrowthLevel;
        ResilienzaCreativa: GrowthLevel;
    };
}

export interface InferredConceptMastery {
    concept: string;
    mastery: MasteryLevel;
    pillarType: PillarType;
}

export interface QualitativeAnalysisData {
    classEnergy: InferredClassEnergy[];
    studentGrowth: InferredStudentGrowth[];
    conceptMastery: InferredConceptMastery[];
}